First implementation of LOOP and ILOOP instructions. Not yet tested on real hardware.

diff --git a/pru_sw/utils/pasm_source/rtests/Makefile b/pru_sw/utils/pasm_source/rtests/Makefile
--- a/pru_sw/utils/pasm_source/rtests/Makefile
+++ b/pru_sw/utils/pasm_source/rtests/Makefile
@@ -7,7 +7,8 @@ EVALUATOR ?= ../reval.py
 
 SRCS :=	xchg.p xin.p xout.p \
 	zero.p fill.p \
-	sxchg.p sxin.p sxout.p
+	sxchg.p sxin.p sxout.p \
+	loop.p iloop.p
 
 OBJS := $(patsubst %.p,%.bin, ${SRCS})
 LSTS := $(patsubst %.p,%.txt, ${SRCS})
@@ -18,11 +19,16 @@ all : $(OBJS)
 
 %.bin : %.p $(MAKEFILE) $(ASSEMBLER) $(EVALUATOR)
 	@echo -n "  TEST	$<"
-	@$(ASSEMBLER) -b -L $< $(subst .p,, $<) 2>&1 >/dev/null
-	@$(EVALUATOR) $@ 2>&1 >/dev/null ; \
+	@$(ASSEMBLER) -b -L $< $(subst .p,, $<) 2>&1 >/dev/null ; \
 		if test $$? -ne 0 ; \
-		then echo "	- FAIL" ; \
-		else echo "	- OK" ; \
+		then \
+			$(ASSEMBLER) -b -L $< $(subst .p,, $<) ; \
+		else \
+			$(EVALUATOR) $@ 2>&1 >/dev/null ; \
+			if test $$? -ne 0 ; \
+			then echo "	- FAIL" ; \
+			else echo "	- OK" ; \
+			fi \
 		fi
 
 clean:
